### ISSUE TITLE
benchmark fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [bartavelle/stateWriter#5]
```
       Building benchmark 'bench' for stateWriter-0.4.0..
       [1 of 1] Compiling Main
        
       /var/stackage/work/unpack-dir/unpacked/stateWriter-0.4.0-ad21de6c98d3e426f15b0faee209e73a8eb1825efbc4e70818e9786e288aa06d/ben
ch/bench.hs:23:5: error: [GHC-88464]
           Variable not in scope: unless :: Bool -> m () -> m ()
          |
       23 |     unless (v == 0) $ do
          |     ^^^^^^
        
       /var/stackage/work/unpack-dir/unpacked/stateWriter-0.4.0-ad21de6c98d3e426f15b0faee209e73a8eb1825efbc4e70818e9786e288aa06d/ben
ch/bench.hs:25:9: error: [GHC-88464]
           Variable not in scope: when :: Bool -> m () -> m a0
          |
       25 |         when (v `mod` 11 == 0) $ tellaction v
          |         ^^^^
```
Please open if PR to re-enable it in stackage

**Comment by juhp** [comment]
ps It would be nice to have the actual github project https url in the .cabal file.

**Comment by bartavelle** [comment]
I am away til mid July 😢 will fix it when I get back!
